### PR TITLE
improved detection of keymapping 

### PR DESCRIPTION
**Pull request by abecodes**

### CODE REVIEW

**Comment by abecodes** [comment]
@akinsho If I use the iterator over all 'i' mappings while using snap, compe and tabout it only prints the mapping from compe...can you pull and start again and tell me, if it prints more mappings for you?

**Comment by akinsho** [comment]
Will have a go tomorrow and report back as I'm away from my computer atm

**Comment by abecodes** [comment]
Sounds good. 

I adapted your lazy load event and key settings and if I trigger snap first thing the buffer opens up I can reproduce the wrong mapping. I fixed it by ignoring local mappings and only applying the global one, if one exists. Can you verify it works now as intended?

Out of curiosity: Why do you use snap and telescope? Aren't they doing the same?

**Comment by akinsho** [comment]
@abecodes I think that's fixed the issue 👍🏿. Seems to be mapped correctly now despite telescope and snap 🚀 thanks.

Regarding why, I use both, tbh I have a few sets of plugins with overlapping functionality since I can't decide which I want to invest in long term. In the case of snap/telescope, if you use telescope on a really large repository or just a medium-sized one and try to grep the behaviour is intolerably slow (for me anyway) snap is non-blocking. The main issue is that it doesn't have an ecosystem. Basically it's very hard to go without telescope since there are loads of extensions for it and I even create some in my plugins, but it's not as usable for work for me. I'm waiting till a fix lands to improve its performance and I might leave snap or if snap'a development picks up again, and it develops an API then I might leave telescope 🤷🏿

**Comment by abecodes** [comment]
@akinsho Finally xD Thanks for your support along the way 💯  I merged it into master, would you mind testing it again, I had some merging/rebasing to do and it was a long night ;)

Ahh, that lifts my confusions, thanks for explaining. Maybe I will give snap a spin too. Thinking about it, I mostly use Telescope for emojis, so I never encountered issues with speed.

**Comment by akinsho** [comment]
Seems to work fine in the master branch 👍🏿 thanks for the fix 🥇

**Comment by abecodes** [comment]
You are the man, thanks for the awesome colab, was a pleasure 👍  Stay healthy

**Pull request merged**
